import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Apple, Dumbbell, Home, Users } from "lucide-react";
import { useState } from "react";
export const AdminHeader = ({ onLogout }) => {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const toggleMenu = () => {
        setIsMenuOpen(!isMenuOpen);
    };
    return (_jsxs("header", { className: "bg-indigo-800 text-white shadow-md", children: [_jsxs("div", { className: "container mx-auto px-4 py-4 flex justify-between items-center", children: [_jsx("h1", { className: "text-2xl font-bold", children: "FITPOWER ADMIN" }), _jsxs("div", { className: "flex items-center space-x-6", children: [_jsxs("nav", { className: "hidden md:flex space-x-6", children: [_jsxs("a", { href: "/admin", className: "hover:text-blue-200 transition flex items-center space-x-1", children: [_jsx(Home, { size: 18 }), _jsx("span", { children: "Inicio" })] }), _jsxs("a", { href: "/admin/nutritionists", className: "hover:text-blue-200 transition flex items-center space-x-1", children: [_jsx(Apple, { size: 18 }), _jsx("span", { children: "Nutricionistas" })] }), _jsxs("a", { href: "/admin/clients", className: "hover:text-blue-200 transition flex items-center space-x-1", children: [_jsx(Users, { size: 18 }), _jsx("span", { children: "Clientes" })] }), _jsxs("a", { href: "/admin/trainers", className: "hover:text-blue-200 transition flex items-center space-x-1", children: [_jsx(Dumbbell, { size: 18 }), _jsx("span", { children: "Entrenadores" })] })] }), _jsxs("div", { className: "relative", children: [_jsx("button", { onClick: toggleMenu, className: "flex items-center justify-center bg-indigo-600 hover:bg-indigo-700 text-white px-3 py-1 rounded text-sm", children: isMenuOpen ? "▲" : "▼" }), isMenuOpen && (_jsx("div", { className: "absolute right-0 top-full mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20", children: _jsx("button", { onClick: onLogout, className: "block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-red-300", children: "Cerrar sesi\u00F3n" }) }))] })] })] }), isMenuOpen && (_jsx("div", { className: "md:hidden bg-indigo-800 text-white", children: _jsxs("nav", { className: "container mx-auto px-4 py-2 flex flex-col space-y-2", children: [_jsxs("a", { href: "/admin/nutritionists", className: "hover:bg-indigo-700 py-2 px-4 rounded transition flex items-center space-x-2", children: [_jsx(Apple, { size: 18 }), _jsx("span", { children: "Nutricionistas" })] }), _jsxs("a", { href: "/admin/clients", className: "hover:bg-indigo-700 py-2 px-4 rounded transition flex items-center space-x-2", children: [_jsx(Users, { size: 18 }), _jsx("span", { children: "Clientes" })] }), _jsxs("a", { href: "/admin/trainers", className: "hover:bg-indigo-700 py-2 px-4 rounded transition flex items-center space-x-2", children: [_jsx(Dumbbell, { size: 18 }), _jsx("span", { children: "Entrenadores" })] })] }) }))] }));
};
